let currentFilter="all";
const $=id=>document.getElementById(id);
const formatOdds=v=>v.toFixed(2).replace(".",",");
const formatValue=v=>`${v>=0?"+":""}${v.toFixed(1).replace(".",",")} %`;
function filtered(){return MATCHES.filter(m=>currentFilter==="all"||currentFilter==="top"&&m.topPick||m.tour===currentFilter)}
function show(m){$("detailTitle").textContent=`${m.player1} vs. ${m.player2}`;$("detailMeta").textContent=`${m.tour} · ${m.event} · Start ${m.start}`;$("probabilityText").textContent=`${m.probability} %`;$("probabilityBar").style.width=`${m.probability}%`;$("fairOdds").textContent=formatOdds(m.fairOdds);$("marketOdds").textContent=formatOdds(m.marketOdds);$("valueText").textContent=formatValue(m.value);$("confidence").textContent=`${m.confidence} / 100`;$("recommendation").textContent=m.pick;$("reasons").innerHTML=m.reasons.map((r,i)=>`<div class="reason"><span class="dot${i===m.reasons.length-1?" risk":""}"></span><span>${r}</span></div>`).join("")}
function render(){const list=$("matchList");const ms=filtered();list.innerHTML="";$("matchCount").textContent=ms.length;$("pickCount").textContent=ms.filter(m=>m.topPick).length;ms.forEach((m,i)=>{const card=document.createElement("article");card.className=`match${i===0?" selected":""}`;card.innerHTML=`<div class="match-top"><span class="match-meta">${m.tour} · ${m.event} · ${m.start}</span><span class="badge">${m.topPick?"Top-Pick":"Analyse"}</span></div><div class="player"><span class="player-name">${m.player1}</span><span class="odds">${formatOdds(m.odds1)}</span></div><div class="player"><span class="player-name">${m.player2}</span><span class="odds">${formatOdds(m.odds2)}</span></div><div class="pick-row"><span>Empfehlung: <strong>${m.pick}</strong></span><span>${m.probability} %</span></div>`;card.onclick=()=>{document.querySelectorAll(".match").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");show(m)};list.appendChild(card)});if(ms[0])show(ms[0])}
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;render()});
$("refreshButton").onclick=()=>{$("lastUpdated").textContent=`aktualisiert ${new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}`};
$("todayTitle").textContent=new Date().toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"});
$("ladderList").innerHTML=LADDER.map(x=>`<div class="ladder-item"><span class="ladder-time">${x.time}</span><span>${x.label}</span><span class="ladder-odds">${x.odds}</span></div>`).join("");
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"))}
render();