let all=[],filter="all";const $=id=>document.getElementById(id);
const odd=v=>Number.isFinite(Number(v))?Number(v).toFixed(2).replace(".",","):"–";
const status=v=>v==="upcoming"?"Bevorstehend":v==="live-or-started"?"Läuft/gestartet":v||"Unbekannt";
function selected(){return all.filter(m=>filter==="all"||filter==="priced"&&Number.isFinite(Number(m.odds1))&&Number.isFinite(Number(m.odds2))||m.tour===filter)}
function details(m){$("title").textContent=`${m.player1} vs. ${m.player2}`;$("meta").textContent=`${m.tour} · ${m.event}`;$("p1").textContent=m.player1;$("p2").textContent=m.player2;$("o1").textContent=odd(m.odds1);$("o2").textContent=odd(m.odds2);$("event").textContent=m.event||"–";$("start").textContent=`${m.date||""} ${m.start||""}`.trim()||"–";$("status").textContent=status(m.status);$("detailSource").textContent=m.source||"The Odds API"}
function render(){const ms=selected(),box=$("matches");box.innerHTML="";$("count").textContent=ms.length;$("priced").textContent=ms.filter(m=>Number.isFinite(Number(m.odds1))&&Number.isFinite(Number(m.odds2))).length;if(!ms.length){box.innerHTML='<div class="empty">Für diesen Filter sind aktuell keine Matches vorhanden.</div>';return}ms.forEach((m,i)=>{const c=document.createElement("article");c.className=`card${i===0?" selected":""}`;c.innerHTML=`<div class="top"><span>${m.tour} · ${m.event} · ${m.date||""} ${m.start||""}</span><span>${status(m.status)}</span></div><div class="player"><span>${m.player1}</span><b>${odd(m.odds1)}</b></div><div class="player"><span>${m.player2}</span><b>${odd(m.odds2)}</b></div>`;c.onclick=()=>{document.querySelectorAll(".card").forEach(x=>x.classList.remove("selected"));c.classList.add("selected");details(m)};box.appendChild(c)});details(ms[0])}
async function load(){try{const r=await fetch(`./data/matches.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();all=Array.isArray(p.matches)?p.matches:[];const d=p.generatedAt?new Date(p.generatedAt):null;$("source").textContent=all.length?"Live- und kommende Matches mit verfügbaren EU-Matchwinnerquoten.":"Der Datenlauf ist eingerichtet, aktuell wurden keine passenden Wettbewerbe geliefert.";$("updated").textContent=d?d.toLocaleString("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Noch kein Lauf";$("sysSource").textContent=p.source||"–";$("tz").textContent=p.timezone||"Europe/Berlin";$("quota").textContent=p.quota?.remaining??"–";render()}catch(e){all=[];$("matches").innerHTML=`<div class="empty">Daten konnten nicht geladen werden.<br>${e.message}</div>`;$("updated").textContent="Ladefehler";$("count").textContent="0";$("priced").textContent="0"}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
$("refresh").onclick=load;$("date").textContent=new Date().toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));load();